Add script to replace Go module path in files
kubernetes-sigs/prow pull request #84
Opened 2024-02-02 06:49 UTC by timwangmusic

This script replaces references of `k8s.io/test-infra` with `sigs.k8s.io/prow`. Then it restores imports using packages from the test-infra repo. We will remove those references in a follow up PR. The end state for the current PR is the code compiles and we can run unit tests.

/cc @cjwagner @airbornepony @listx

2024-02-02 17:34 UTC, airbornepony requested changes

2024-02-02 21:33 UTC, airbornepony commented
I believe this script should include a `go fmt` command to re-sort imports that have been renamed, and probably `go mod tidy` to refresh those. (Both seem needed for the goal of passing tests per the description.)

2024-02-06 18:08 UTC, listx commented on hack/scripts/replace-module-path.sh
> +    escaped_string=$(printf '%s\n' "${strings[i]}" | sed 's/[[\.*^$/]/\\&/g')
This escaping doesn't need to happen. I think you are operating under the assumption that `sed` requires you to put patterns inside `s/FROM/TO/`, but the forward slashes here (which collide with the forward slashes in the input) are not required at all. For example you can do `s|FROM|TO|` or `s,FROM,TO,` or use any other punctuation character for the pattern delimiters.

2024-02-06 18:08 UTC, listx commented on hack/scripts/replace-module-path.sh
> +# restore imports using packages from the test-infra repo
Comments should try to explain more than what is happening. For example, *why* are you undoing the sed work from above to use the old import paths? The answer to that question would be very helpful for readers/reviewers. Thanks.

2024-03-02 20:57 UTC, timwangmusic commented
We will move the dependencies before adding a script.

2024-03-02 20:57 UTC, closed without merging